name: On Push

on:
  push:
    branches:
    - main
    - track/**

jobs:

  on-push:
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@kf-5425-fix-names
    permissions:
      pull-requests: read
    secrets: inherit
    with:
      microk8s-channel: 1.32-strict/stable
      juju-channel: 3.6/stable
      python-version: "3.8"
      rockcraft-channel: latest/edge # pinning this until this issue is open https://github.com/canonical/knative-rocks/issues/12
